### ISSUE TITLE
天猫店铺全店商品信息爬虫

### ISSUE THREAD

**Issue by linwumingshi** [Hopetree/E-commerce-crawlers#3]
天猫店铺全店商品信息爬虫，代码报错。。。提取总页码数提取不到

**Comment by Hopetree** [comment]
@Lin222 接口经常变动的，我的爬虫都是很早的了，要根据新接口去改代码

**Comment by Diane513** [comment]
> @Lin222 接口经常变动的，我的爬虫都是很早的了，要根据新接口去改代码

请问能给个学习方向吗，就如何修改这个代码
